services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - ${BE_PORT}:8000
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql-db
    ports:
      - "${MYSQL_CUSTOM_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
